SushmaElectrical.UI/Controllers/CartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using SushmaElectrical.Entities;
using SushmaElectrical.Repositories.Interfaces;
using SushmaElectrical.ViewModels;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using SushmaElectrical.Extensions;
using SushmaElectrical.Repositories.Implementations;

namespace SushmaElectrical.UI.Controllers
{
    [Authorize]
    public class CartsController : Controller
    {
        private readonly ICartRepo _cartRepo;



        private readonly IProductRepo _productRepo;

        private readonly IHttpContextAccessor _httpContextAccessor;



        public CartsController(ICartRepo cartRepo, IProductRepo productRepo, IHttpContextAccessor httpContextAccessor)
        {
            _cartRepo = cartRepo;
            _productRepo = productRepo;
            _httpContextAccessor = httpContextAccessor;
        }





        public async Task<IActionResult> AddItem(int productId, int qty = 1, int redirect = 0)
        {
            try
            {
                var cartCount = await _cartRepo.AddItem(productId, qty);
                if (redirect != 0)
                {
                    return RedirectToAction("GetUserCart");
                }
                return Ok(new { cartCount });

            }
            catch (Exception)
            {

                throw;
            }
        }





        public async Task<IActionResult> RemoveItem(int productId)
        {
            try
            {
                if (productId <= 0)
                {
                    throw new Exception("Invalid id");
                }
                var cartCount = await _cartRepo.RemoveItem(productId);

                // TempData["success"] = "Item removed from cart.";

                return RedirectToAction("GetUserCart");
            }
            catch (Exception)
            {

                throw;
            }

        }






        public async Task<IActionResult> GetUserCart()
        {
            try
            {
                // Retrieve the cart from the repository
                var cartData = await _cartRepo.GetUserCart();


                // Pass the populated cartViewModel to the view
                return View(cartData);
            }
            catch (Exception ex)
            {
                // Handle exceptions more gracefully
                // Log the exception
                Console.WriteLine($"An error occurred: {ex.Message}");
                // You might want to redirect to an error page or show an error message
                return RedirectToAction("Index", "Home");
            }
        }



      



        public async Task<IActionResult> GetTotalItemInCart()
        {
            try
            {
                int cartItem = await _cartRepo.GetCartItemCount();
                return Ok(cartItem);
            }
            catch (Exception)
            {

                throw;
            }

        }






    }
}

SushmaElectrical.UI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SushmaElectrical.Entities;
using SushmaElectrical.Repositories.Interfaces;

namespace SushmaElectrical.UI.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderRepo _orderRepo;
        private readonly ILogger<HomeController> _logger;

        public OrderController(IOrderRepo orderRepo, ILogger<HomeController> logger)
        {
            _orderRepo = orderRepo;
            _logger = logger;
        }



        public async Task<IActionResult> Orders()
        {
            try
            {
                var orders = await _orderRepo.GetUserOrder();
                if (orders == null)
                {
                    TempData["error"] = "No orders found.";
                    return View(new List<OrderViewModel>());
                }

                var orderViewModels = orders.Select(order => new OrderViewModel
                {
                    Id = order.Id,
                    ProductName = order.orderDetails.Select(od => od.Product.ProductName).FirstOrDefault(),
                    ProductImage = order.orderDetails.Select(od => od.Product.ImagesUrl).FirstOrDefault(),
                    GrossPrice = order.orderDetails.Select(od => od.UnitPrice * od.Quantity).Sum(),
                    Quantity = order.orderDetails.Sum(od => od.Quantity),
                    OrderStatus = order.OrderStatus,
                    OrderDate=order.CreatedDate,
                    
                    OrderDetails = order.orderDetails.ToList() // Assigning the list of OrderDetails directly
                }).ToList();

                return View(orderViewModels);
            }
            catch (Exception ex)
            {
                // Log the exception
                _logger.LogError(ex, "An error occurred while fetching user orders.");

                // Set an error message to display an alert in the view
                TempData["error"] = "An error occurred while fetching user orders.";

                // Redirect to a different action or return a view with a message
                return RedirectToAction("Error", "Home");
            }
        }





        public async Task<IActionResult> CancelOrder(int orderId)
        {
            try
            {
                if (orderId <= 0)
                {
                    TempData["error"] = "Invalid orderId.";
                    return RedirectToAction("Index", "Home");
                }

                var success = await _orderRepo.CancelOrder(orderId);

                if (!success)
                {
                    TempData["error"] = "Failed to cancel the order.";
                    return RedirectToAction("Index", "Home");
                }

                TempData["success"] = "Order cancelled successfully.";
                return RedirectToAction("Index", "Home"); 
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while cancelling the order.");

                TempData["error"] = "An error occurred while cancelling the order.";

                return RedirectToAction("Error", "Home");
            }
        }






        public async Task<IActionResult> OrderIssue(int orderId)
        {
            try
            {
                if (orderId <= 0)
                {
                    TempData["error"] = "Invalid orderId.";
                    return RedirectToAction("Index", "Home");
                }

                var success = await _orderRepo.OrderIssue(orderId);

                if (!success)
                {
                    TempData["error"] = "Failed to report issue for the order.";
                    return RedirectToAction("Index", "Home");
                }

                TempData["success"] = "Order issue reported successfully.";
                return RedirectToAction("Index", "Home"); 
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while reporting issue for the order.");

                TempData["error"] = "An error occurred while reporting issue for the order.";

                return RedirectToAction("Error", "Home");
            }
        }


    }
}

SushmaElectrical.UI/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;
using SushmaElectrical.Entities;
using SushmaElectrical.Repositories.Implementations;
using SushmaElectrical.Repositories.Interfaces;
using SushmaElectrical.UI.DDL;
using SushmaElectrical.ViewModels;
using SushmaElectrical.ViewModels.Utility;
using static SushmaElectrical.ViewModels.CategoryViewModel;

namespace SushmaElectrical.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly ICategoryRepo categoryRepo;
        private readonly IProductRepo productRepo;
        private readonly IOrderRepo orderRepo;
        private readonly IUtilityRepo utilityRepo;
        private readonly ILogger<ProductsController> _logger;

        private readonly DDLHelpers ddl;
        private string ImageFolder = "ProductImages";




        public ProductsController(ICategoryRepo categoryRepo, IProductRepo productRepo,
            IUtilityRepo utilityRepo, DDLHelpers ddl, IOrderRepo orderRepo, ILogger<ProductsController> logger)
        {
            this.categoryRepo = categoryRepo;
            this.productRepo = productRepo;
            this.utilityRepo = utilityRepo;
            this.ddl = ddl;
            this.orderRepo = orderRepo;
            _logger = logger;
        }









        public async Task<IActionResult> Index(int PageNo = 1, int pageSize = 10)

        {
            try
            {
                var products = await productRepo.GetProducts(PageNo, pageSize);

                var productViewModels = products
                    .Select(product => new ProductViewModel
                    {
                        Id = product.Id,
                        ProductName = product.ProductName,
                        CategoryName = product.Category.CategoryName,
                        Brand = product.Brand,
                        PowerRating = product.PowerRating,
                        ModelNumber = product.ModelNumber,
                        Voltage = product.Voltage,
                        NetPrice = product.NetPrice,
                        Quantity = product.Quantity
                    })
                    .ToList();

                var totalItems = await productRepo.GetTotalProductCount();

                var pagedViewModel = new PagedProductViewModel
                {
                    Products = productViewModels,
                    PageInfo = new PageInfo
                    {
                        PageNo = PageNo,
                        PageSize = pageSize,
                        TotalItems = totalItems
                    }
                };

                return View(pagedViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while processing the request.");
                TempData["ErrorMessage"] = "An error occurred while processing your request. Please try again later.";
                return RedirectToAction("Error", "Home");
            }
        }








        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var product = await productRepo.GetById(id);
                if (product == null)
                {
                    return NotFound();
                }

                var productDetails = new ProductViewModel
                {
                    Id = product.Id,
                    ProductName = product.ProductName,
                    ProductImages = product.ImagesUrl,
                    CategoryName = product.Category?.CategoryName,
                    Description = product.Description,
                    Brand = product.Brand,
                    ModelNumber = product.ModelNumber,
                    PowerRating = product.PowerRating,
                    Voltage = product.Voltage,
                    NetPrice = product.NetPrice,
                    Discount = product.Discount,
                    Tax = product.GST,
                    GrossPrice = product.GrossPrice,
                    Quantity = product.Quantity
                };

                return View(productDetails);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while retrieving product details.");
                TempData["ErrorMessage"] = "An error occurred while retrieving product details. Please try again later.";
                return RedirectToAction("Error", "Home");
            }
        }





        public async Task<IActionResult> CreateProduct()
        {
            try
            {
                var categoryList = await ddl.GetCategoryList();
                ViewBag.CategoryList = categoryList;
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while retrieving category list for product creation.");
                TempData["ErrorMessage"] = "An error occurred while retrieving category list for product creation. Please try again later.";
                return RedirectToAction("Error", "Home");
            }
        }






        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProduct(CreateProductViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool IsExistingProduct = await productRepo.ProductExists(vm.ProductName, vm.Brand, vm.PowerRating, vm.Voltage);
                    if (IsExistingProduct)
                    {
                        ModelState.AddModelError(string.Empty, "Product with this name already exists.");
                        TempData["ErrorMessage"] = "Product with this name already exists.";
                        var existingCategoryList = await ddl.GetCategoryList();
                        ViewBag.CategoryList = existingCategoryList;
                        return View(vm);
                    }

                    var product = new Product
                    {
                        ProductName = vm.ProductName,
                        Description = vm.Description,
                        CategoryId = vm.CategoryId,
                        Brand = vm.Brand,
                        PowerRating = vm.PowerRating,
                        ModelNumber = vm.ModelNumber,
                        Voltage = vm.Voltage,
                        NetPrice = vm.NetPrice,
                        Discount = vm.Discount,
                        Quantity = vm.Quantity,
                        GST = vm.Tax,
                        GrossPrice = vm.GrossPrice
                    };

                    if (vm.ProductImages != null && vm.ProductImages.Count > 0)
                    {
                        var filesCollection = new FormFileCollection();
                        foreach (var file in vm.ProductImages)
                        {
                            var formFile = new FormFile(file.OpenReadStream(), 0, file.Length, file.Name, file.FileName)
                            {
                                Headers = file.Headers,
                                ContentType = file.ContentType
                            };
                            filesCollection.Add(formFile);
                        }

                        var savedImageUrls = await utilityRepo.SaveImages(ImageFolder, filesCollection);
                        product.ImagesUrl = string.Join(",", savedImageUrls);
                    }

                    await productRepo.Save(product);
                    TempData["success"] = "Product saved successfully!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Please fix the errors below.";
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while creating the product.");
                TempData["error"] = "An error occurred while creating the product. Please try again later.";
            }

            var categoryList = await ddl.GetCategoryList();
            ViewBag.CategoryList = categoryList;
            return View(vm);
        }







        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var product = await productRepo.GetById(id);
                if (product == null)
                {
                    return NotFound();
                }

                var editproductViewModel = new EditProductViewModel
                {
                    Id = product.Id,
                    ProductName = product.ProductName,
                    Description = product.Description,
                    CategoryId = product.CategoryId,
                    ImageUrl = product.ImagesUrl,
                    PowerRating = product.PowerRating,
                    Brand = product.Brand,
                    ModelNumber = product.ModelNumber,
                    Voltage = product.Voltage,
                    Tax = product.GST,
                    Quantity = product.Quantity,
                    Discount = product.Discount,
                    NetPrice = product.NetPrice,
                    GrossPrice = product.GrossPrice
                };
                var categoryList = await ddl.GetCategoryList();
                ViewBag.CategoryList = categoryList;

                return View(editproductViewModel);
            }
            catch (Exception ex)
            {
                TempData["error"] = "An error occurred while editing the product. Please try again later.";
                _logger.LogError(ex, "An error occurred while editing the product.");
                throw;
            }

        }

SushmaElectrical.UI/Views/Shared/_AdminNav.cshtml
<nav class="navbar navbar-expand-lg  bg-dark  fixed-top" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Sushma Electrical</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fa-solid fa-house"></i> Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-controller="Categories" asp-action="Index"><i class="fa-solid fa-layer-group"></i>  Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-controller="Products" asp-action="Index"><i class="fa-solid fa-boxes-stacked"></i> Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-controller="Dashboard" asp-action="GetUserOrders"><i class="fa-solid fa-clipboard-list"></i> Orders</a>
                </li>
                <li class="nav-item">
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

SushmaElectrical.UI/Views/Shared/_AlertPartial.cshtml
@*  @if (TempData["success"] != null)
{
    <div id="successAlert" class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> @TempData["success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["warning"] != null)
{
    <div id="warningAlert" class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Warning!</strong> @TempData["warning"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["error"] != null)
{
    <div id="errorAlert" class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> @TempData["error"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["info"] != null)
{
    <div id="infoAlert" class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>Info!</strong> @TempData["info"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<script>
    // Add fade-out effect to alerts after 3 seconds
    window.setTimeout(function () {
        $("#successAlert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
        $("#warningAlert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
        $("#errorAlert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
        $("#infoAlert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 3000);
</script>


 *@
@*  <style>
    .floating-alert {
        position: fixed;
        top: 20px; /* Adjust this value to position the alert vertically */
        right: 20px; /* Adjust this value to position the alert horizontally */
        z-index: 1000; /* Ensure the alert is above other content */
        width: 300px; /* Adjust this value to control the width of the alert */
    }

 </style> *@

@if (TempData["success"] != null)
{
    <div id="successAlert" class="floating-alert alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> @TempData["success"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["warning"] != null)
{
    <div id="warningAlert" class="floating-alert alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Warning!</strong> @TempData["warning"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["error"] != null)
{
    <div id="errorAlert" class="floating-alert alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> @TempData["error"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["info"] != null)
{
    <div id="infoAlert" class="floating-alert alert alert-info alert-dismissible fade show" role="alert">
        <strong>Info!</strong> @TempData["info"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<script>
    // Add fade-out effect to alerts after 3 seconds
    window.setTimeout(function () {
        $(".floating-alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 3000);
</script>

SushmaElectrical.UI/Views/Shared/_CustomerNav.cshtml
<nav class="navbar navbar-expand-lg bg-primary fixed-top" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">SushmaElectrical</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-action="Index" asp-controller="Home">
                        <i class="fa-solid fa-house"></i> Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-action="GetUserCart" asp-controller="Carts">
                        <span class="badge bg-info text-dark" id="cartCount">0</span>
                        <i class="fa-solid fa-cart-shopping">
                        </i>  My Cart
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-action="Orders" asp-controller="Order"><i class="fa-solid fa-bag-shopping"></i>  My Order</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-action="About" asp-controller="Home"><i class="fa-solid fa-address-card"></i> About</a>
                </li>
             
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

SushmaElectrical.UI/Views/Shared/_DefaultNav.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Sushma Electrical</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
@*                     <a class="nav-link" href="#">Link 1</a>
 *@                </li>
                <li class="nav-item">
@*                     <a class="nav-link" href="#">Link 2</a>
 *@                </li>
                <partial name="_LoginPartial" />
            </ul>
        </div>
    </div>
</nav>

SushmaElectrical.UI/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json
@using SushmaElectrical.Infrastructure.GlobalConfiguration
@using SushmaElectrical.ViewModels
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SushmaElectrical.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/unitedtheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="~/SushmaElectrical.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />



</head>
<body>
    <header>
        @if (User.IsInRole(Role.Admin_Role))
        {
            <partial name="_AdminNav" />
        }
        else if (User.Identity.IsAuthenticated)
        {
            <partial name="_CustomerNav" />
        }
        else
        {
            <partial name="_DefaultNav" />
        }
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            <div>
                <partial name="_AlertPartial" />
            </div>
            @RenderBody()
        </main>
    </div>
@* 
    <footer class="footer">
        <div class="container">
            &copy; 2024 - SushmaElectrical.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>


    <!-- Bootstrap JS -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>